name: ci cd prueba

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Ejecutar test
        run: node --test

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Simular build
        run: |
          mkdir dist
          cp index.js dist/index.js
          echo "build completado"

      - name: Guardar artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: dist/

  deploy:
    name: Deploy
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Descargar artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build

      - name: Simular deploy
        run: |
          echo "archivos recibidos:"
          ls -la
          echo "desplegando aplicación..."
          node index.js