name: cdi cd prueba

on: 
  push:
    branch: 
      - main

jobs:
  test:
    name: testing
    runs-on: ubuntu-latest

  steps:
    - name: descargar repositorios
      uses: actions/checkouts@v4

    - name: configuracion node.jobs
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: ejecutar aplicacion
      runs: node index.js

  deploy:
    name: deploy
    needs: testing
    runs-on: ubuntu-latest

    steps:
      - name: Simular deploy
        run: |
          echo: "iniciando despliegue"
          echo: "aplicacion desplegada"